create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
create TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(200) NOT NULL,
  description VARCHAR(500),
  owner_id BIGINT NOT NULL,
  available BOOLEAN DEFAULT true,
  CONSTRAINT item_id PRIMARY KEY (id),
  CONSTRAINT owner_id FOREIGN KEY (owner_id) REFERENCES users(id)
);
create TABLE IF NOT EXISTS bookings(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id BIGINT NOT NULL,
    date_start_booking TIMESTAMP NOT NULL,
    date_end_booking TIMESTAMP NOT NULL,
    user_booking BIGINT NOT NULL,
    status varchar(50),
    CONSTRAINT booking_id PRIMARY KEY (id),
    CONSTRAINT item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT user_booking FOREIGN KEY (user_booking) REFERENCES users(id)
);
create TABLE IF NOT EXISTS comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment varchar(500) NOT NULL,
    user_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    post_date TIMESTAMP NOT NULL,
    CONSTRAINT commnet_id PRIMARY KEY (id),
    CONSTRAINT item_id FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT user_commented FOREIGN KEY (user_id) REFERENCES users(id)
);